### ISSUE TITLE
Is this used by Diep.io already?

### ISSUE THREAD

**Issue by haykam821** [Matheus28/m28n-web#1]
Hello! I’m your friendly neighborhood stalker from the Diep.io community. As a fan of development with Node.js, I wanted to know if you were already using this system with Diep.io, considering you use Vultr and Linode to host your 8 types of servers.

If so, then I can tell my friends on Discord that you actually know JavaScript and don’t just use Emscripten to convert the contents of your `d` folder to the mess that is `d.js`.

**Comment by Matheus28** [comment]
Please don't spam my public repositories with irrelevant issues.

Thank you.

**Comment by haykam821** [comment]
Ok, fair enough.

Rest In Peace Diep.io in the process.
